## Day 1: Logistic Regression from Scratch

In [69]:
import numpy as np


In [70]:
X = np.array([
    [1, 1],
    [2, 2],
    [3, 3],
    [4, 4],
    [5, 5]
])

y = np.array([0, 0, 0, 1, 1])

print(X)
print(y)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[0 0 0 1 1]


In [71]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [72]:
import numpy as np

In [73]:
weights = np.zeros(2)
bias = 0

print("Weights:", weights)
print("Bias:", bias)

Weights: [0. 0.]
Bias: 0


In [74]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [75]:
z = np.dot(X, weights) + bias
predictions = sigmoid(z)

print("Z:", z)
print("Predictions:", predictions)

Z: [0. 0. 0. 0. 0.]
Predictions: [0.5 0.5 0.5 0.5 0.5]


In [76]:
loss = -np.mean(
    y * np.log(predictions) +
    (1 - y) * np.log(1 - predictions)
)

print("Loss:", loss)

Loss: 0.6931471805599453


In [77]:
dw = (1 / len(y)) * np.dot(X.T, (predictions - y))
db = (1 / len(y)) * np.sum(predictions - y)

print("Gradient of weights:", dw)
print("Gradient of bias:", db)

Gradient of weights: [-0.3 -0.3]
Gradient of bias: 0.1


## Day 2: Gradient Descent and Model Evaluation

In [52]:
learning_rate = 0.01

weights = weights - learning_rate * dw
bias = bias - learning_rate * db

print("Updated weights:", weights)
print("Updated bias:", bias)

Updated weights: [0.25027053 0.25027053]
Updated bias: -1.4269799579569231


In [53]:
predictions = 1 / (1 + np.exp(-(np.dot(X, weights) + bias)))

print("New predictions:", predictions)

New predictions: [0.28364774 0.39510632 0.51865215 0.63995856 0.74568419]


In [54]:
loss = -(1 / len(y)) * np.sum(
    y * np.log(predictions) + (1 - y) * np.log(1 - predictions)
)

print("New loss:", loss)

New loss: 0.46145117161356836


In [55]:
dw = (1 / len(y)) * np.dot(X.T, (predictions - y))
db = (1 / len(y)) * np.sum(predictions - y)

print("New gradient of weights:", dw)
print("New gradient of bias:", db)

New gradient of weights: [-0.01638559 -0.01638559]
New gradient of bias: 0.11660979237039044


In [56]:
weights = weights - learning_rate * dw
bias = bias - learning_rate * db

print("Updated weights:", weights)
print("Updated bias:", bias)

Updated weights: [0.25043439 0.25043439]
Updated bias: -1.428146055880627


In [57]:
predictions = 1 / (1 + np.exp(-(np.dot(X, weights) + bias)))

print("New predictions:", predictions)

New predictions: [0.28347742 0.39498427 0.51860647 0.63999191 0.74577378]


In [58]:
loss = -(1 / len(y)) * np.sum(
    y * np.log(predictions) + (1 - y) * np.log(1 - predictions)
)

print("New loss:", loss)

New loss: 0.46130984948755227


In [59]:
dw = (1 / len(y)) * np.dot(X.T, (predictions - y))
db = (1 / len(y)) * np.sum(predictions - y)

print("New gradient of weights:", dw)
print("New gradient of bias:", db)

New gradient of weights: [-0.01637961 -0.01637961]
New gradient of bias: 0.11656677150276643


In [60]:
weights = weights - learning_rate * dw
bias = bias - learning_rate * db

print("Updated weights:", weights)
print("Updated bias:", bias)

Updated weights: [0.25059818 0.25059818]
Updated bias: -1.4293117235956545


In [61]:
for epoch in range(1000):

    # Prediction
    predictions = 1 / (1 + np.exp(-(np.dot(X, weights) + bias)))

    # Gradient
    dw = (1 / len(y)) * np.dot(X.T, (predictions - y))
    db = (1 / len(y)) * np.sum(predictions - y)

    # Update
    weights = weights - learning_rate * dw
    bias = bias - learning_rate * db

    # Loss
    loss = -(1 / len(y)) * np.sum(
        y * np.log(predictions) + (1 - y) * np.log(1 - predictions)
    )

    if epoch % 100 == 0:
        print("Epoch:", epoch, "Loss:", loss)

Epoch: 0 Loss: 0.4611686315687156
Epoch: 100 Loss: 0.44755567565347354
Epoch: 200 Loss: 0.43488605157260063
Epoch: 300 Loss: 0.42307152368040635
Epoch: 400 Loss: 0.41203322849551605
Epoch: 500 Loss: 0.40170068817513016
Epoch: 600 Loss: 0.3920108999601432
Epoch: 700 Loss: 0.3829075070912392
Epoch: 800 Loss: 0.37434005145951377
Epoch: 900 Loss: 0.36626330494323495


In [62]:
print("Final weights:", weights)
print("Final bias:", bias)

predictions = 1 / (1 + np.exp(-(np.dot(X, weights) + bias)))

print("Final predictions:", predictions)

Final weights: [0.38965176 0.38965176]
Final bias: -2.4182374575953065
Final predictions: [0.16261017 0.29741657 0.47992907 0.66796084 0.81431266]


In [63]:
predicted_classes = (predictions >= 0.5).astype(int)

print("Predicted classes:", predicted_classes)

Predicted classes: [0 0 0 1 1]


In [64]:
accuracy = np.mean(predicted_classes == y)

print("Model Accuracy:", accuracy * 100, "%")

Model Accuracy: 100.0 %


In [65]:
cm = np.zeros((2, 2), dtype=int)

for actual, predicted in zip(y, predicted_classes):
    cm[int(actual), int(predicted)] += 1

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[3 0]
 [0 2]]


In [66]:
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]
TP = cm[1, 1]

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 3
False Positive: 0
False Negative: 0
True Positive: 2


In [67]:
precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1_score = 2 * (precision * recall) / (precision + recall)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)

Precision: 1.0
Recall: 1.0
F1 Score: 1.0


In [68]:
print("Actual Labels:       ", y)
print("Predicted Probabilities:", predictions)
print("Predicted Classes:   ", predicted_classes)

Actual Labels:        [0 0 0 1 1]
Predicted Probabilities: [0.16261017 0.29741657 0.47992907 0.66796084 0.81431266]
Predicted Classes:    [0 0 0 1 1]
