In [25]:
import numpy as np


In [26]:
X = np.array([
    [1, 1],
    [2, 2],
    [3, 3],
    [4, 4],
    [5, 5]
])

y = np.array([0, 0, 0, 1, 1])

print(X)
print(y)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[0 0 0 1 1]


In [27]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
import numpy as np

In [29]:
weights = np.zeros(2)
bias = 0

print("Weights:", weights)
print("Bias:", bias)

Weights: [0. 0.]
Bias: 0


In [30]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [31]:
z = np.dot(X, weights) + bias
predictions = sigmoid(z)

print("Z:", z)
print("Predictions:", predictions)

Z: [0. 0. 0. 0. 0.]
Predictions: [0.5 0.5 0.5 0.5 0.5]


In [32]:
loss = -np.mean(
    y * np.log(predictions) +
    (1 - y) * np.log(1 - predictions)
)

print("Loss:", loss)

Loss: 0.6931471805599453


In [33]:
dw = (1 / len(y)) * np.dot(X.T, (predictions - y))
db = (1 / len(y)) * np.sum(predictions - y)

print("Gradient of weights:", dw)
print("Gradient of bias:", db)

Gradient of weights: [-0.3 -0.3]
Gradient of bias: 0.1


In [34]:
learning_rate = 0.01

weights = weights - learning_rate * dw
bias = bias - learning_rate * db

print("Updated weights:", weights)
print("Updated bias:", bias)

Updated weights: [0.003 0.003]
Updated bias: -0.001


In [35]:
predictions = 1 / (1 + np.exp(-(np.dot(X, weights) + bias)))

print("New predictions:", predictions)

New predictions: [0.50125    0.50274997 0.5042499  0.50574975 0.50724949]


In [36]:
loss = -(1 / len(y)) * np.sum(
    y * np.log(predictions) + (1 - y) * np.log(1 - predictions)
)

print("New loss:", loss)

New loss: 0.6912923044288435


In [37]:
dw = (1 / len(y)) * np.dot(X.T, (predictions - y))
db = (1 / len(y)) * np.sum(predictions - y)

print("New gradient of weights:", dw)
print("New gradient of bias:", db)

New gradient of weights: [-0.28425078 -0.28425078]
New gradient of bias: 0.10424982115772058


In [38]:
weights = weights - learning_rate * dw
bias = bias - learning_rate * db

print("Updated weights:", weights)
print("Updated bias:", bias)

Updated weights: [0.00584251 0.00584251]
Updated bias: -0.0020424982115772056


In [39]:
predictions = 1 / (1 + np.exp(-(np.dot(X, weights) + bias)))

print("New predictions:", predictions)

New predictions: [0.50241061 0.50533168 0.50825239 0.51117253 0.51409191]


In [40]:
loss = -(1 / len(y)) * np.sum(
    y * np.log(predictions) + (1 - y) * np.log(1 - predictions)
)

print("New loss:", loss)

New loss: 0.6896077733371746


In [41]:
dw = (1 / len(y)) * np.dot(X.T, (predictions - y))
db = (1 / len(y)) * np.sum(predictions - y)

print("New gradient of weights:", dw)
print("New gradient of bias:", db)

New gradient of weights: [-0.26940384 -0.26940384]
New gradient of bias: 0.10825182455291607


In [42]:
weights = weights - learning_rate * dw
bias = bias - learning_rate * db

print("Updated weights:", weights)
print("Updated bias:", bias)

Updated weights: [0.00853655 0.00853655]
Updated bias: -0.003125016457106366


In [43]:
for epoch in range(1000):

    # Prediction
    predictions = 1 / (1 + np.exp(-(np.dot(X, weights) + bias)))

    # Gradient
    dw = (1 / len(y)) * np.dot(X.T, (predictions - y))
    db = (1 / len(y)) * np.sum(predictions - y)

    # Update
    weights = weights - learning_rate * dw
    bias = bias - learning_rate * db

    # Loss
    loss = -(1 / len(y)) * np.sum(
        y * np.log(predictions) + (1 - y) * np.log(1 - predictions)
    )

    if epoch % 100 == 0:
        print("Epoch:", epoch, "Loss:", loss)

Epoch: 0 Loss: 0.6880746830695066
Epoch: 100 Loss: 0.6475292022670812
Epoch: 200 Loss: 0.6193440764562345
Epoch: 300 Loss: 0.5934799518821675
Epoch: 400 Loss: 0.5697270278005521
Epoch: 500 Loss: 0.5478889756955604
Epoch: 600 Loss: 0.5277841923321035
Epoch: 700 Loss: 0.5092462987378424
Epoch: 800 Loss: 0.49212399928775946
Epoch: 900 Loss: 0.4762805004725339


In [44]:
print("Final weights:", weights)
print("Final bias:", bias)

predictions = 1 / (1 + np.exp(-(np.dot(X, weights) + bias)))

print("Final predictions:", predictions)

Final weights: [0.25010656 0.25010656]
Final bias: -1.4258129986299002
Final predictions: [0.28381825 0.39522846 0.51869786 0.63992519 0.74559452]


In [45]:
predicted_classes = (predictions >= 0.5).astype(int)

print("Predicted classes:", predicted_classes)

Predicted classes: [0 0 1 1 1]


In [46]:
accuracy = np.mean(predicted_classes == y)

print("Model Accuracy:", accuracy * 100, "%")

Model Accuracy: 80.0 %


In [48]:
cm = np.zeros((2, 2), dtype=int)

for actual, predicted in zip(y, predicted_classes):
    cm[int(actual), int(predicted)] += 1

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[2 1]
 [0 2]]


In [49]:
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]
TP = cm[1, 1]

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 2
False Positive: 1
False Negative: 0
True Positive: 2


In [50]:
precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1_score = 2 * (precision * recall) / (precision + recall)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)

Precision: 0.6666666666666666
Recall: 1.0
F1 Score: 0.8


In [51]:
print("Actual Labels:       ", y)
print("Predicted Probabilities:", predictions)
print("Predicted Classes:   ", predicted_classes)

Actual Labels:        [0 0 0 1 1]
Predicted Probabilities: [0.28381825 0.39522846 0.51869786 0.63992519 0.74559452]
Predicted Classes:    [0 0 1 1 1]
